### ISSUE TITLE
cannot resolve host "postgresql"

### ISSUE THREAD

**Issue by uralsemih** [cradlepoint/kubernetes-helm-chart-pgbouncer#39]
I've running postgresql on-prem kubernetes where postgresql svc name is " postgres-stage-postgresql-helm".. I specified this host as below under databases but somehow the value of POSTGRESQL_HOST set postgresql..

What ı am doing wrong? Do I have to set POSTGRESQL_HOST as an environment variable and override. it ?

$ kubectl exec -ti pgbouncer-pgbouncer-864cdbc44d-2b2tn -n database sh
$ printenv
POSTGRESQL_HOST=postgresql

Here is values.yaml

```
databases:
  postgres:
    host: postgres-stage-postgresql-helm
    port: 64000
    user: test
    dbname: postgres
    auth_user: pgbouncer
```
Here is the log of pgbouncer pod

```
pgbouncer 07:05:42.05 INFO  ==> ** Starting PgBouncer setup **
pgbouncer 07:05:42.06 INFO  ==> Validating settings in PGBOUNCER_* env vars...
pgbouncer 07:05:42.07 INFO  ==> Initializing PgBouncer...
pgbouncer 07:05:42.08 INFO  ==> Waiting for PostgreSQL backend to be accessible
cannot resolve host "postgresql": lookup postgresql on 10.254.0.10:53: no such host
cannot resolve host "postgresql": lookup postgresql on 10.254.0.10:53: no such host
```
